<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-3QKDSQ4" failures="1" tests="2" name="Default test(failed)(failed)" time="0.092" errors="0" timestamp="2022-06-30T17:01:11 IST">
  <testcase classname="failedXMLFile.FailedFileRerun" name="tc3" time="0.013"/>
  <testcase classname="failedXMLFile.FailedFileRerun" name="tc4" time="0.014">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at failedXMLFile.FailedFileRerun.tc4(FailedFileRerun.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- tc4 -->
  <testcase classname="failedXMLFile.FailedFileRerun" name="tc2" time="0.0">
    <ignored/>
  </testcase> <!-- tc2 -->
  <testcase classname="failedXMLFile.FailedFileRerun" name="tc1" time="0.0">
    <ignored/>
  </testcase> <!-- tc1 -->
</testsuite> <!-- Default test(failed)(failed) -->
